language: 
      - "python"
env:
  - CODECOV_TOKEN="bae1d058-97bf-4d5e-8d8e-e3ecc89f4c22"
python:
      - "3.6"

before_install:

virtualenv:
      system-site-packages: false

# Install dependencies
install:
      - "pip3 install -r requirements.txt"

script: 
      - "pytest --cov"

after_success:
- "codecov"
